"""empty message

Revision ID: eed8fc6494d0
Revises: 
Create Date: 2019-09-11 21:16:57.429854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed8fc6494d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('invitations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('invited_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'invited_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    op.drop_table('dates')
    # ### end Alembic commands ###
